add send_templated_email
ex-aws/ex_aws_ses pull request #3
Opened 2018-06-13 02:15 UTC by xfumihiro

2018-08-05 14:00 UTC, lessless commented on lib/ex_aws/ses.ex
> +    | {:from_arn, String.t}
I don't see `from_arn` option at https://docs.aws.amazon.com/ses/latest/APIReference/API_SendTemplatedEmail.html

2018-08-05 14:04 UTC, lessless requested changes
Hi @xfumihiro! 

There are few things here - `from_arn` doesn't seems to be an options that SES can recognize and second I want to ask to add test coverage for the `send_templated_email_opt`.

Thanks for the PR!

2018-08-06 13:55 UTC, xfumihiro commented
done!

2018-08-06 14:21 UTC, samhstn commented on test/lib/ses_test.exs
> +      assert expected == ExAws.SES.send_templated_email(
`ExAws.SES` -> `SES` (it's aliased in this module)

2018-08-07 00:45 UTC, lessless commented
Great stuff @xfumihiro ! One last thing before merging it in is a parser test - https://github.com/ex-aws/ex_aws_ses/blob/master/test/lib/ses/parser_test.exs :)

2018-08-07 00:46 UTC, lessless requested changes
Great stuff @xfumihiro ! One last thing before merging it in is a parser test - https://github.com/ex-aws/ex_aws_ses/blob/master/test/lib/ses/parser_test.exs :)

2018-08-08 03:15 UTC, xfumihiro commented
done!

2018-08-08 03:57 UTC, lessless approved these changes
Great! Thanks for contribution ❤️ !

2018-08-08 03:57 UTC, lessless approved these changes

2018-08-08 13:06 UTC, merged

2018-08-08 13:59 UTC, lessless commented
@xfumihiro available in 2.0.2 https://hex.pm/packages/ex_aws_ses/2.0.2